keystone:
  admin-password: password

mysql:
  dataset-size: 15%

nova-cloud-controller:
#  network-manager: Neutron

quantum-gateway:
  instance-mtu: 1400

nova-compute:
  config-flags: 'vnc_enabled=False,libvirt_disk_prefix=vd,libvirt_use_virtio_for_bridges=False'
  flat-interface: eth0